### ISSUE TITLE
Bug or idea for workaround: KendoGrid.Instance.SaveasPDF()

### ISSUE THREAD

**Issue by JanBrandenburger-LSF** [iceteagroup/Wisej-Ext-Kendo#1]
Hi ITG-Team,
there is an interesting effect using the this.grvDaten.Instance.saveAsPDF(); method.

When you click the tool-button there happens nothing.
You have to click anywhere at the application and only then the download starts. (see attached video)

I used your code from Kendo.Test project and implemented it.
[2020-10-29_09h35_35.zip](https://github.com/iceteagroup/Wisej-Ext-Kendo/files/5457028/2020-10-29_09h35_35.zip)

Any ideas?

Thanks.

Jan

**Comment by LRufenacht** [comment]
Hi Jan,

There is an issue with the Kendo extensions I am addressing now. This is the correct way to prompt the download:

```
private void kendoGrid1_WebRequest(object sender, WebRequestEventArgs e)
{
	switch (e.Request.QueryString["action"])
	{
		case "export":
			// prepare for download.
			this.ExportDocument(e.Request.Form["base64"], e.Request.Form["fileName"], e.Response);
			break;
		}
	}
}

private void ExportDocument(string base64, string fileName, HttpResponse response)
{
	var bytes = Convert.FromBase64String(base64);
	response.AddHeader("Content-Disposition", $"attachment; filename={fileName}");
	response.OutputStream.Write(bytes, 0, bytes.Length);
}
```

The Kendo widget uses a [proxy URL](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/excel.proxyurl) to upload the pdf or excel document to the server.

You can also open the Wisej.Web.Ext.Kendo solution and remove the `filterOptions` portion of kendoGrid.js if you don't need the document on the server. This should increase the responsitivity of the download as well as it doesn't need to be uploaded first.

I'll update the GitHub repository and demo.wisej.com/Kendo as well.

If you have any questions or issues please let me know!

Best regards,
Levie

**Comment by JanBrandenburger-LSF** [comment]
Hi Levie,
it works wonderful!
Thank you.
Jan
