### ISSUE TITLE
New components in the KENDO Suite

### ISSUE THREAD

**Issue by JanBrandenburger-LSF** [iceteagroup/Wisej-Ext-Kendo#3]
Hi Levie,
I don't know if you read it, but in the last two releases of Kendo UI for jQuery new components were added. (https://www.telerik.com/support/whats-new/kendo-jquery-ui)

Possibly the captcha, orgchart and taskboard, maybe the heatmap chart are of particular interest.

If you have some time, it would be cool to extend the Wisej adaptation.

It's however not a high priority.

Thanks a lot.

Best from Germany,
Jan

**Comment by LRufenacht** [comment]
Hi Jan,

Thanks for the update!

I'll look into upgrading the extensions.

Regards,
Levie
